SELECT * FROM CUSTOMERS WHERE ID = 18

/*WHERE CUSTOMERNAME = 'ALÝ*/
/*WHERE CITY = 'ÝSTANBUL' */
/*WHERE CITY <> 'ISTANBUL' EÞÝT DEÐÝLDÝR*/
/*WHERE NOT CITY = 'ÝSTANBUL' EÞÝT DEÐÝLDÝR*/
/* WHERE BIRTHDATE > '19900101' YIL,AY,GUN */
/*
WHERE BIRTHDATE < '19890101'*/
/*WHERE BIRTHDATE BETWEEN '19900101' AND '19981231'*/
/*WHERE AGE BETWEEN '19900101' AND '19981231'*/
/*WHERE AGE BETWEEN 22 AND 25 */
/*WHERE CUSTOMERNAME LIKE 'ALÝ%' ALÝ ÝLE BAÞLAYAN*/
/*WHERE CUSTOMERNAME LIKE '%A'  SONU A OLAN */
 /* WHERE CUSTOMERNAME LIKE '%ALAN%' ÝÇÝNDE ALAN GEÇEN*/
 /*WHERE CUSTOMERNAME NOT LIKE 'ALÝ%' ALÝ ÝLE BAÞLAMAYAN */
 /*WHERE CITY IN ('ÝSTANBUL' , 'ANKARA','ÝZMÝR','BURSA' ) ÝÇÝNDE ÝSTANBUL,ANKARA,ÝZMÝR,BURSA OLAN */
 /*WHERE CITY IN ('ÝSTANBUL', 'ANKARA','ÝZMÝR','BURSA')
 UPDATE CUSTOMERS SET GENDER = 'KADIN' WHERE GENDER = 'K' */

 DELETE FROM CUSTOMERS WHERE ID = 18
