/*SELECT DISTINCT CITY FROM CUSTOMERS*/
/*SELECT  DISTINCT CITY,DISTRICT FROM CUSTOMERS


WHERE CITY = 'ÝSTANBUL'*/

/*SELECT  DISTINCT GENDER FROM CUSTOMERS

WHERE CITY = 'ÝSTANBUL'*/


SELECT  DISTINCT AGE FROM CUSTOMERS

WHERE CITY = 'ÝSTANBUL'



