SELECT * FROM CUSTOMERS

/*ORDER BY ID  DEFAULT ASC */
/*ORDER BY CUSTOMERNAME DESC*/
/*ORDER BY CITY*/
/*ORDER BY CITY ASC ,CUSTOMERNAME DESC*/
/*WHERE CITY='ÝSTANBUL'
ORDER BY CITY,DISTRICT,CUSTOMERNAME */
/*WHERE CITY='ÝSTANBUL'
ORDER BY 3,2,1,4,5,6  KOLON NUMARALARI*/
