/*SELECT TOP 10 * FROM CUSTOMERS ÝLK 10 */
/*SELECT TOP 100 PERCENT * FROM CUSTOMERS 
ORDER BY CUSTOMERNAME 100%100'Ü*/
/*SELECT TOP 50 PERCENT * FROM CUSTOMERS 
ORDER BY CUSTOMERNAME %50'SÝNÝ GETÝRDÝ */
/*SELECT TOP 10 PERCENT * FROM CUSTOMERS 
ORDER BY CUSTOMERNAME %10'U GETÝRDÝ*/
SELECT TOP 1 *FROM CUSTOMERS 
ORDER BY CUSTOMERNAME