/*SELECT *FROM SALES */
/*SELECT COUNT(*) FROM SALES TABLODA KAÇ SATIR VAR  */
/*SELECT * FROM SALES ORDER BY AMOUNT   AMOUNTE GÖRE SIRALA */
/*SELECT MIN(AMOUNT),MAX(AMOUNT),COUNT(*) FROM SALES   EN AZ MÝKTAR,EN ÇOK MÝKTAR,KAÇ TANE */
/*SELECT MIN(AMOUNT),MAX(AMOUNT),COUNT(*),SUM(AMOUNT),AVG(AMOUNT)FROM SALES  ENAZ MÝKTAR,ENÇOK MÝKTAR,KAÇTANE,TOPLAM MIKTAR,ORTALAMA MIKTAR */
SELECT MIN(TOTALPRICE),MAX(TOTALPRICE),COUNT(FICHENO),SUM(TOTALPRICE),AVG(TOTALPRICE) FROM SALES
WHERE CITY = 'ADANA'/*MIN TUTAR , MAKS TUTAR,TOPLAM TUTAR,ORTALAMA TUTAR*/

SELECT MIN(TOTALPRICE),MAX(TOTALPRICE),COUNT(FICHENO),SUM(TOTALPRICE),AVG(TOTALPRICE) FROM SALES
WHERE CITY = 'ÝSTANBUL'