/*SELECT
CITY,
MIN(TOTALPRICE)AS ENDUSUKFIYAT ,MAX(TOTALPRICE) AS MAKSIMUMFIYAT,COUNT(FICHENO) AS FISHMIKTARI,SUM(TOTALPRICE) AS TOPLAMTUTAR,AVG(TOTALPRICE) AS ORTALAMATUTAR
FROM SALES 
GROUP BY CITY ORDER BY CITY  */


/*SELECT
CITY,
MIN(TOTALPRICE)AS MINPRICE ,MAX(TOTALPRICE) AS MAXPRICE,COUNT(FICHENO) AS ROWCOUNT_,SUM(TOTALPRICE) AS TOTALPRICE,AVG(TOTALPRICE) AS AVGPRICE
FROM SALES 
GROUP BY CITY  
ORDER BY SUM(TOTALPRICE)*/
/*
SELECT TOP 10  ÝLK 10 MAÐAZA
CITY,SUM(TOTALPRICE) ÞEHÝR,TOPLAM FÝYATMIKTARI
FROM SALES     ,SALES TABLOSUNDA
GROUP BY CITY   ,ÞEHRE GÖRE GRUPLA
ORDER BY SUM(TOTALPRICE) DESC   ,TOPLAMTUTARA GÖRE YÜKSEKTEN DÜÞÜÐE SIRALA
*/







