/* SELECT CONVERT (DATE,DATE_) AS DATE2,*  DATE2 ADINDA YENÝ SANAL KOLON OLUÞTU
FROM SALES WHERE CITY ='ANKARA'   ÞEHRÝ ANKARA OLAN
ORDER BY DATE_         DATE GÖRE SIRALANDI

SELECT CONVERT(DATETIME,'2019-01-01 08:46:10.000') ÇEVÝRÝLDÝ TARÝH SAATE */
/*
SELECT * FROM SALES  
UPDATE SALES SET DATE2=CONVERT(DATE,DATE_) DATE2 ALANI DATE DÖNÜÞTÜRÜLDÜ
*/
SELECT * FROM SALES WHERE CITY = 'ANKARA' 
AND DATE2 = '2019-01-01'
ORDER BY DATE_
