SELECT CITY,SUM(TOTALPRICE) AS TOTALPRICE, 
COUNT(DISTINCT CUSTOMERNAME) CUSTOMERCOUNT 

FROM SALES 

GROUP BY CITY 
HAVING COUNT (DISTINCT CUSTOMERNAME) > 500 
AND SUM(TOTALPRICE)>300000 

ORDER BY SUM(TOTALPRICE) DESC 