
/*
CREATE TABLE TEST (ID INT IDENTITY(1,1),CUSTOMERNAME VARCHAR(50))  tabloyu oluþturur

DROP TABLE TEST  tabloyu siler */ 
 
 
 /*PRIMARY KEYLÝ TABLO */

 CREATE TABLE TEST2 (
 ID TINYINT IDENTITY (1,1),
 COUNTRY VARCHAR(50)
 CONSTRAINT PK_TEST2 PRIMARY KEY CLUSTERED (ID ASC))
 