SELECT
CT.CITY,COUNT(U.ID) AS KULLANICISAYISI,COUNT(DISTINCT D.DISTRICT) AS ILCESAYISI
FROM 
USERS U,ADDRESS A,COUNTRYID C,CITIES CT,
TOWNS T,DISTRCITS D
WHERE U.ID=A.USERID AND C.ID=A.COUNTRYID AND CT.ID=A.CITYID
AND T.ID=A.TOWNID --AND U.ID =1
AND D.ID = A.DISTRICTID 

GROUP BY CT.CITY