SELECT U.*,A.ADDRESSTEXT,U.EMAIL,A.ADDRESSTEXT,C.COUNTRY,
CT.CITY,T.TOWN,D.DISTRICT
FROM 
USERS U  
JOIN ADDRESS A ON A.USERID=U.ID
JOIN COUNTRYID C ON C.ID=A.COUNTRYID
JOIN CITIES CT ON CT.ID = A.CITYID
JOIN TOWNS T ON T.ID=A.TOWNID
JOIN DISTRCITS D ON D.ID=A.DISTRICTID
