/* SEHIRLERE GORE VERÝLEN TOPLAM SÝPARÝÞ MÝKTARÝ
*/

SELECT CT.CITY AS 
SEHIRADI,SUM(OD.LINETOTAL)
TOPLAMSIPARIS_TUTARI,SUM(OD.AMOUNT)
TOPLAMSIPARIS_ADEDI,
COUNT(OD.ID)TOPLAMSIPARIS_SAYISI
FROM ORDERS O 
INNER JOIN USERS U ON U.ID=O.USERID 
INNER JOIN ADDRESS A ON A.ID=O.ADDRESSID
INNER JOIN CITIES CT ON CT.ID = A.CITYID
INNER JOIN TOWNS T ON T.ID=A.TOWNID
INNER JOIN DISTRICTS D ON D.ID=A.DISTRICTID
INNER JOIN PAYMENTS P ON P.ORDERID=O.ID
INNER JOIN INVOICES I ON I.ORDERID = O.ID
INNER JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
INNER JOIN ITEMS ITM ON ITM.ID=OD.ITEMID


GROUP BY CT.CITY
ORDER BY 2 DESC